spring:
  application:
    name: NetLab
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username:
    password:
  security:
    filter:
      order: -100

mybatis:
  configuration:
    map-underscore-to-camel-case: true